services:
  postgres:
    container_name: postgres-sql-consolt
    image: postgres
    environment:
      POSTGRES_USER: consolt
      POSTGRES_PASSWORD: consolt
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: consolt
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-consolt
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  keycloak:
    container_name: keycloak-consolt
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-demo
 
    command:
      - "start-dev"

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
